query get_staff($id:uuid!){
  items:staffs_by_pk(id:$id){
    staff_id
    AIB_exp
    bio_exp
    disability_exp
    DVLA_exp
    epilepsy_exp
    first_aid_exp
    passport_exp
    safeguarding_exp
    taxi_badge_exp
    address
    name
    phone_number
    role
    status
  }
}