query ($filter:booking_bool_exp){
  items:booking(where:$filter){
    pickup_date
    id
    driver_name
    driver_phone
    PA_name
    PA_phone
    vehicle_reg
    route
    first_pickup_time
    first_pickup_address
    first_drop_off
    first_pupil_name
    first_pupil_phone
    second_drop_off
    second_pupil_name
    second_pupil_phone
    second_pickup_address
    seventh_pickup_address
    third_drop_off
    third_pupil_name
    third_pupil_phone
    third_pickup_address
    fourth_drop_off
    fourth_pupil_name
    fourth_pupil_phone
    fourth_pickup_address
    fifth_drop_off
    fifth_pupil_name
    fifth_pupil_phone
    fifth_pickup_address
    sixth_drop_off
    sixth_pupil_name
    sixth_pupil_phone
    sixth_pickup_address
    seventh_drop_off
    seventh_pupil_name
    seventh_pupil_phone
    seventh_pickup_address
    eighth_drop_off
    eighth_pupil_name
    eighth_pupil_phone
    eighth_pickup_address
    status
  }
}